# Generated by Django 4.2.7 on 2025-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilageassessment',
            name='avg_temp',
            field=models.FloatField(default=25.0, help_text='Average temperature (°C)'),
        ),
        migrations.AddField(
            model_name='spoilageassessment',
            name='days_stored',
            field=models.IntegerField(default=0, help_text='Days stored'),
        ),
        migrations.AlterField(
            model_name='spoilageassessment',
            name='spoilage_risk',
            field=models.FloatField(default=0.0, help_text='Spoilage risk percentage (0-100)'),
        ),
    ]
