# Generated by Django 4.2.7 on 2025-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_spoilageassessment_avg_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilageassessment',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether an SNS notification has been sent'),
        ),
    ]
