name: Deploy to AWS Fargate

on:
  push:
    branches: [ ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      env:
        ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: latest
      run: |
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${ECR_REPO}:${IMAGE_TAG}"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Prepare ECS Task Definition from Template
      env:
        IMAGE_URI: ${{ env.IMAGE_URI }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
        AWS_SNS_TOPIC_ARN: ${{ secrets.AWS_SNS_TOPIC_ARN }}
        AWS_DYNAMODB_TABLE: ${{ secrets.AWS_DYNAMODB_TABLE }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SQS_QUEUE_URL: ${{ secrets.AWS_SQS_QUEUE_URL }}
        TASK_EXECUTION_ROLE_ARN: ${{ secrets.TASK_EXECUTION_ROLE_ARN }}
      run: |
        cp ecs-task-def.json.template ecs-task-def.json
        sed -i "s|<IMAGE_URI>|$IMAGE_URI|g" ecs-task-def.json
        sed -i "s|<AWS_STORAGE_BUCKET_NAME>|$AWS_STORAGE_BUCKET_NAME|g" ecs-task-def.json
        sed -i "s|<AWS_S3_REGION_NAME>|$AWS_S3_REGION_NAME|g" ecs-task-def.json
        sed -i "s|<AWS_SNS_TOPIC_ARN>|$AWS_SNS_TOPIC_ARN|g" ecs-task-def.json
        sed -i "s|<AWS_DYNAMODB_TABLE>|$AWS_DYNAMODB_TABLE|g" ecs-task-def.json
        sed -i "s|<AWS_DEFAULT_REGION>|$AWS_DEFAULT_REGION|g" ecs-task-def.json
        sed -i "s|<AWS_SQS_QUEUE_URL>|$AWS_SQS_QUEUE_URL|g" ecs-task-def.json
        sed -i "s|<TASK_EXECUTION_ROLE_ARN>|$TASK_EXECUTION_ROLE_ARN|g" ecs-task-def.json

    - name: Register ECS Task Definition
      id: register-task-def
      run: |
        TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://ecs-task-def.json \
          --query "taskDefinition.taskDefinitionArn" --output text)
        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

    - name: Deploy to ECS Service
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ secrets.ECS_SERVICE_NAME }} \
          --task-definition ${{ env.TASK_DEF_ARN }} \
          --force-new-deployment
